### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [edowning87/prj-rev-bwfs-dasmoto#5]
(Meets Expectations)

Nice job with this project! It looks like you have a solid understanding of how HTML and CSS work together for display of content. And great that you're using multiple selectors for styling shared properties, as that avoid repetition- keep up the good work!

One thing you could look more into is the uses of classes and ids for styling your elements. Generally, classes are meant to be applied to multiple elements while IDs are specific to one. Here is a great resource on that: https://css-tricks.com/the-difference-between-id-and-class/

As a further challenge, try expanding this page and play around with adding some of your own elements to it. Happy coding!

**Comment by edowning87** [comment]
Thank you for your feedback
